var assert = require('assert');
var ubique = require('../../index.js');

suite('linalgebra',function () {
console.log('Testing linalgebra/det ...');
test('det', function (done) {



assert.deepEqual(ubique.det([[1,5],[6,2]]),-28);
assert.deepEqual(ubique.det([[2,2],[2,3]]),2);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->