var assert = require('assert');
var ubique = require('../../index.js');

suite('elmath',function () {
console.log('Testing elmath/erfcinv ...');
test('erfcinv', function (done) {



assert.deepEqual(ubique.erfcinv(1.5),-0.476936236121904);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->