var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/annreturn ...');
test('annreturn', function (done) {



assert.deepEqual(ubique.annreturn([0.015,0.02],12,20),[0.008973187316161368,0.011952442696057552]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->