var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/cagr ...');
test('cagr', function (done) {

var x = [100,98,101.5,103];
var y = [99.8,96.5,101.1,95.8];

assert.deepEqual(ubique.cagr(x,4),0.007417071777732875);
assert.deepEqual(ubique.cagr(ubique.cat(1,x,y),4),[[0.007417071777732875,-0.010174263005363726]]);
assert.deepEqual(ubique.cagr(ubique.cat(1,x,y),2,0),[-0.0010005005006258338,-0.007682572182156844,-0.0019723885079668824,-0.03558458775347195]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->