var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/drawdown ...');
test('drawdown', function (done) {

var x = [0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];
var y = [-0.005,0.081,0.04,-0.037,-0.061,0.058,-0.049,-0.021,0.062,0.058];

assert.deepEqual(ubique.drawdown(ubique.cumprod(ubique.plus(x,1))),{"dd":[0,0,0,0.00900000000000004,0,0,0,0,0.013999999999999995,0],"ddrecov":[0,0,0,4,0,0,0,0,9,0],"maxdd":0.013999999999999995,"maxddrecov":[8,9]});
assert.deepEqual(ubique.drawdown(ubique.cat(1,ubique.cumprod(ubique.plus(x,1)),ubique.cumprod(ubique.plus(y,1)))),[[{"dd":[0,0,0,0.00900000000000004,0,0,0,0,0.013999999999999995,0],"ddrecov":[0,0,0,4,0,0,0,0,9,0],"maxdd":0.013999999999999995,"maxddrecov":[8,9]},{"dd":[0,0,0,0.03700000000000013,0.09574300000000016,0.04329609400000011,0.09017458539400008,0.1092809191007261,0.05405633608497113,0],"ddrecov":[0,0,0,4,5,6,7,8,9,0],"maxdd":0.1092809191007261,"maxddrecov":[3,8]}]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->