var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/drawdown ...');
test('drawdown', function (done) {

var x = [0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];

assert.deepEqual(ubique.drawdown(x),{"dd":[0,0,0,0.00900000000000004,0,0,0,0,0.013999999999999995,0],"ddrecov":[0,0,0,4,0,0,0,0,9,0],"maxdd":0.013999999999999995,"maxddrecov":[8,9]});


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->