var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/irr ...');
test('irr', function (done) {



assert.deepEqual(ubique.irr([250000,25000,-10000,-285000]),0.024712563094781776);
assert.deepEqual(ubique.irr([74.2,37.1,-104.4],[0,1,2],2),-0.07410820570460687);
assert.deepEqual(ubique.irr([250000,25000,-10000,-285000],[0,45,69,90],90),0.07692283872311291);
assert.deepEqual(ubique.irr([74.2,37.1,-104.4],[0,14,31],31),-0.07271456460699813);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->