var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/martinratio ...');
test('martinratio', function (done) {

var x = [0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];
var y = [-0.005,0.081,0.04,-0.037,-0.061,0.058,-0.049,-0.021,0.062,0.058];
var cat = ubique.cat;

assert.deepEqual(ubique.martinratio(x,0,12),44.42545597931942);
assert.deepEqual(ubique.martinratio(cat(1,x,y),0,12,'return',1),[[44.42545597931942,2.438364078885411]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->