var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/mdietz ...');
test('mdietz', function (done) {

var ev = 104.4,bv = 74.2,cf = 37.1,cfd = 14, cd = 31;
var ev = 1200,bv = 1000,cf = [10,50,35,20],cfd = [15,38,46,79],cd = 90;

assert.deepEqual(ubique.mdietz(ev,bv,cf,cfd,cd),0.0804331826306382);
assert.deepEqual(ubique.mdietz(ev,bv,cf,cfd,cd),0.0804331826306382);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->