var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/montecarlovar ...');
test('montecarlovar', function (done) {

var x = [0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];

assert.deepEqual(ubique.montecarlovar(x,0.95,1,0,1,10000),0.067812956568023);
assert.deepEqual(ubique.montecarlovar(ubique.std(x),0.99,10,0,100000),27059.296951321987);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->