var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/ret2tick ...');
test('ret2tick', function (done) {

var d = [0.5,-3,2.3];
var e = [[9, 5], [6, 1]];

assert.deepEqual(ubique.ret2tick(0.05),[1,1.05]);
assert.deepEqual(ubique.ret2tick(d,'simple',100),[100,150,-300,-990]);
assert.deepEqual(ubique.ret2tick(e,'simple',100,0),[[100,1000,6000],[100,700,1400]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->