var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/ret2tick ...');
test('ret2tick', function (done) {



assert.deepEqual(ubique.ret2tick([0.5,-3,2.3],'simple',100),[100,150,-300,-990]);
assert.deepEqual(ubique.ret2tick([[9, 5], [6, 1]],'simple',100),[[100,1000,6000],[100,700,1400]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->