var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/ror ...');
test('ror', function (done) {

var q = [[89,23,12],[34,5,70]];

assert.deepEqual(ubique.ror([100,112]),0.1200000000000001);
assert.deepEqual(ubique.ror(q),[[-0.6179775280898876,-0.782608695652174,4.833333333333333]]);
assert.deepEqual(ubique.ror(q,0),[-0.8651685393258427,1.0588235294117645]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->