var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/tick2ret ...');
test('tick2ret', function (done) {



assert.deepEqual(ubique.tick2ret([0.5,-3,2.3]),[-7,-1.7666666666666666]);
assert.deepEqual(ubique.tick2ret([[9, 5], [6, 1]]),[[-0.4444444444444444],[-0.8333333333333334]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->