var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/tick2ret ...');
test('tick2ret', function (done) {

var d = [0.5,-3,2.3];
var e = [[9, 5], [6, 1]];

assert.deepEqual(ubique.tick2ret(d),[-7,-1.7666666666666666]);
assert.deepEqual(ubique.tick2ret(e),[[-0.33333333333333337,-0.8]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->