var assert = require('assert');
var ubique = require('../../index.js');

suite('quants',function () {
console.log('Testing quants/toweekly ...');
test('toweekly', function (done) {

var nd = ubique.datenum(['15-01-15','15-01-23','15-01-30','15-02-04'],'YY-MM-DD');
var nv = [100,99,102,103,98];
var nv2 = [1.2,1.1,1.3,1.4,0.9];
var nvm = ubique.cat(1,nv,nv2);

assert.deepEqual(ubique.toweekly(nd,nv),[[1421280000,1421971200,1422576000,1423008000],[100,99,102,103]]);
assert.deepEqual(ubique.toweekly(nd,nvm),[[1421280000,1421971200,1422576000,1423008000],[[100,1.2],[99,1.1],[102,1.3],[103,1.4]]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->