var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/histc ...');
test('histc', function (done) {

var A = [87,27,45,62,3,52,20,43,74,61];
var B = [12,34,57,43,88,75,89,2,27,29];

assert.deepEqual(ubique.histc(A,[0,20,40,60,80,100]),[{"bins":0,"count":1,"freq":0.1},{"bins":20,"count":2,"freq":0.2},{"bins":40,"count":3,"freq":0.3},{"bins":60,"count":3,"freq":0.3},{"bins":80,"count":1,"freq":0.1},{"bins":100,"count":0,"freq":0}]);
assert.deepEqual(ubique.histc(ubique.cat(1,A,B),[0,50,100]),[[{"bins":0,"count":5,"freq":0.5},{"bins":0,"count":6,"freq":0.6}],[{"bins":50,"count":5,"freq":0.5},{"bins":50,"count":4,"freq":0.4}],[{"bins":100,"count":0,"freq":0},{"bins":100,"count":0,"freq":0}]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->