var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/histc ...');
test('histc', function (done) {

var n = [87,27,45,62,3,52,20,43,74,61];
var q = [[89,23,12],[34,5,70]];
var bins = [0,20,40,60,80,100];

assert.deepEqual(ubique.histc(n,bins),[{"bins":0,"freq":1},{"bins":20,"freq":2},{"bins":40,"freq":3},{"bins":60,"freq":3},{"bins":80,"freq":1},{"bins":100,"freq":0}]);
assert.deepEqual(ubique.histc(q,2,1),[[{"bins":34,"freq":1},{"bins":5,"freq":1},{"bins":12,"freq":1}],[{"bins":61.5,"freq":0},{"bins":14,"freq":0},{"bins":41,"freq":0}],[{"bins":89,"freq":1},{"bins":23,"freq":1},{"bins":70,"freq":1}]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->