var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/mad ...');
test('mad', function (done) {

var a = [[5,6,5],[7,8,-1]];
var c = [5,6,3];

assert.deepEqual(ubique.mad(c) // 1.11111,1.111111111111111);
assert.deepEqual(ubique.mad(a,0) // [0.444444, 3.77778],[0.44444444444444436,3.7777777777777772]);
assert.deepEqual(ubique.mad(a) // [[1, 1, 3]],[[1,1,3]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->