var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/max ...');
test('max', function (done) {

var b = [[-1,3,-1],[4,5,9]];

assert.deepEqual(ubique.max([5,6,-1]) // 6,6);
assert.deepEqual(ubique.max(b,0) // [3, 9],[3,9]);
assert.deepEqual(ubique.max(b) // [[4, 5, 9]],[[4,5,9]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->