var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/mean ...');
test('mean', function (done) {

var a = [[5,6,5],[7,8,-1]];
var c = [5,6,3];

assert.deepEqual(ubique.mean(c),4.666666666666667);
assert.deepEqual(ubique.mean([[5,6,5],[7,8,-1]]),[[5.333333333333333],[4.666666666666667]]);
assert.deepEqual(ubique.mean([[5,6,5],[7,8,-1]],1),[[6,7,2]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->