var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/min ...');
test('min', function (done) {



assert.deepEqual(ubique.min([5,6,-1]),-1);
assert.deepEqual(ubique.min([[-1,3,-1],[4,5,9]]),[[-1],[4]]);
assert.deepEqual(ubique.min([[-1,3,-1],[4,5,9]],1),[[-1,3,-1]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->