var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/min ...');
test('min', function (done) {

var b = [[-1,3,-1],[4,5,9]];

assert.deepEqual(ubique.min([5,6,-1]),-1);
assert.deepEqual(ubique.min(b,0),[-1,4]);
assert.deepEqual(ubique.min(b),[[-1,3,-1]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->