var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/mode ...');
test('mode', function (done) {



assert.deepEqual(ubique.mode([5,6,3]),3);
assert.deepEqual(ubique.mode([[5,6,5],[7,8,-1]]),[[5],[-1]]);
assert.deepEqual(ubique.mode([[5,6,5],[7,8,-1]],1),[[5,6,-1]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->