var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/pdist ...');
test('pdist', function (done) {

var x = [0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];
var y = [-0.005,0.081,0.04,-0.037,-0.061,0.058,-0.049,-0.021,0.062,0.058];

assert.deepEqual(ubique.pdist(x,y,'euclidean'),0.17053152201279387);
assert.deepEqual(ubique.pdist(x,y,'manhattan'),0.4710000000000001);
assert.deepEqual(ubique.pdist(x,y,'chebychev'),0.08700000000000001);
assert.deepEqual(ubique.pdist(x,y,'hamming'),10);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->