var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/prctile ...');
test('prctile', function (done) {

var x = [ 0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];
var y = [-0.005,0.081,0.04,-0.037,-0.061,0.058,-0.049,-0.021,0.062,0.058];
var z = ubique.cat(1,x,y);

assert.deepEqual(ubique.prctile(x,5) // -0.014,-0.014);
assert.deepEqual(ubique.prctile(x,33) // 0.0118,0.011799999999999995);
assert.deepEqual(ubique.prctile(z,5,0) // [-0.005, 0.026, 0.015, -0.037, -0.061, 0.024, -0.049, -0.021, -0.014, 0.039],[-0.005,0.026,0.015,-0.037,-0.061,0.024,-0.049,-0.021,-0.014,0.039]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->