var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/range ...');
test('range', function (done) {

var a = [[5,6,5],[7,8,-1]];
var c = [5,6,3];

assert.deepEqual(ubique.range(c) // 3,3);
assert.deepEqual(ubique.range(a,0) // [1,9],[1,9]);
assert.deepEqual(ubique.range(a) // [[2, 2, 6]],[[2,2,6]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->