var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/skewness ...');
test('skewness', function (done) {

var x = [0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];
var y = [-0.005,0.081,0.04,-0.037,-0.061,0.058,-0.049,-0.021,0.062,0.058];
var z = ubique.cat(1,x,y);

assert.deepEqual(ubique.skewness(x) // 0.617481,0.6174813132481229);
assert.deepEqual(ubique.skewness(x,1) // 0.732243,0.6174813132481229);
assert.deepEqual(ubique.skewness(z) // [[0.617481, -0.118909]],[[0.6174813132481229,-0.11890905913946115]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->