var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/std ...');
test('std', function (done) {

var a = [[5,6,5],[7,8,-1]];
var c = [5,6,3];

assert.deepEqual(ubique.std(c),1.5275252316519465);
assert.deepEqual(ubique.std(c,0),1.5275252316519465);
assert.deepEqual(ubique.std(a,0),[[1.4142135623730951,1.4142135623730951,4.242640687119285]]);
assert.deepEqual(ubique.std(a,0,0),[[1.4142135623730951,1.4142135623730951,4.242640687119285]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->