var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/zscore ...');
test('zscore', function (done) {

var a = [[5,6,5],[7,8,-1]];
var c = [5,6,3];

assert.deepEqual(ubique.zscore(c),[0.2182178902359922,0.8728715609439694,-1.0910894511799623]);
assert.deepEqual(ubique.zscore(c,0),[0.2182178902359922,0.8728715609439694,-1.0910894511799623]);
assert.deepEqual(ubique.zscore(a,0),[[-0.7071067811865475,-0.7071067811865475,0.7071067811865476],[0.7071067811865475,0.7071067811865475,-0.7071067811865476]]);
assert.deepEqual(ubique.zscore(a,0,0),[[-0.5773502691896252,1.154700538379252,-0.5773502691896252],[0.4730161648796401,0.6757373783994859,-1.1487535432791263]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->