var assert = require('assert');
var ubique = require('../../index.js');

suite('stats',function () {
console.log('Testing stats/zscore ...');
test('zscore', function (done) {

var a = [[5,6,5],[7,8,-1]];
var c = [5,6,3];

assert.deepEqual(ubique.zscore(c),[0.2182178902359922,0.8728715609439694,-1.0910894511799623]);
assert.deepEqual(ubique.zscore(c,0),[0.2672612419124242,1.0690449676496974,-1.3363062095621223]);
assert.deepEqual(ubique.zscore(a,0),[[-1,-1,1],[1,1,-1]]);
assert.deepEqual(ubique.zscore(a,0,0),[[-0.7071067811865469,1.4142135623730956,-0.7071067811865469],[0.5793241220216575,0.827605888602368,-1.4069300106240257]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->