var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/arrayfun ...');
test('arrayfun', function (done) {



assert.deepEqual(ubique.arrayfun([1.4,2.3,3],Math.log),[0.3364722366212129,0.8329091229351039,1.0986122886681098]);
assert.deepEqual(ubique.arrayfun([1.4,0,-10],ubique.sign),[1,0,-1]);
assert.deepEqual(ubique.arrayfun([[5,6],[1,3]],Math.pow,3),[[125,216],[1,27]]);
assert.deepEqual(ubique.arrayfun([['cat','concat'],['cattle','catch the catfish']],ubique.strfind,'cat'),[[[0],[3]],[[0],[0,10]]]);
assert.deepEqual(ubique.arrayfun([null,true,'hello',5,NaN],ubique.isnull),[true,false,false,false,false]);
assert.deepEqual(ubique.arrayfun([null,true,'hello',5,NaN],ubique.islogical),[false,true,false,false,false]);
assert.deepEqual(ubique.arrayfun([null,true,'hello',5,NaN],ubique.isstring),[false,false,true,false,false]);
assert.deepEqual(ubique.arrayfun([null,true,'hello',5,NaN],ubique.isnumber),[false,false,false,true,true]);
assert.deepEqual(ubique.arrayfun([null,true,'hello',5,{},undefined,'NaN',NaN],ubique.isnan),[false,false,false,false,false,false,false,true]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->