var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/clock ...');
test('clock', function (done) {



assert.deepEqual([2015,5,4,20,10,22,676],[2015,5,4,20,10,22,676]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->