var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/datevec ...');
test('datevec', function (done) {



assert.deepEqual(ubique.datevec('2015-01-01 03:34:05','YYYY-MM-DD HH:mm:ss'),[2015,1,1,3,34,5,0]);
assert.deepEqual(ubique.datevec(['31-12-2014','31-01-2015'],'DD-MM-YYYY'),[[2014,12,31,0,0,0,0],[2015,1,31,0,0,0,0]]);
assert.deepEqual(ubique.datevec([['31-12-2014','31-01-2015'],['15-02-2015','01-03-2015']],'DD-MM-YYYY'),[[[2014,12,31,0,0,0,0],[2015,1,31,0,0,0,0]],[[2015,2,15,0,0,0,0],[2015,3,1,0,0,0,0]]]);
assert.deepEqual(ubique.datevec(1428236430),[2015,4,5,12,20,30,0]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->