var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/datestr ...');
test('datestr', function (done) {



assert.deepEqual(ubique.datestr(1419980400),"2014-12-30");
assert.deepEqual(ubique.datestr([ 1419984000, 1422662400 ],'DD-MMM-YY'),["31-Dec-14","31-Jan-15"]);
assert.deepEqual(ubique.datestr([ [ 1419984000, 1422662400 ], [ 1423958400, 1425168000 ] ],'YY-MM-DD hh:mm:ss'),[["14-12-31 12:00:00","15-01-31 12:00:00"],["15-02-15 12:00:00","15-03-01 12:00:00"]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->