var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/isarray ...');
test('isarray', function (done) {



assert.deepEqual(ubique.isarray([1.4,2.3,3]),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->