var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/isempty ...');
test('isempty', function (done) {



assert.deepEqual(ubique.isempty([]),true);
assert.deepEqual(ubique.isempty([[]]),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->