var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/isfunction ...');
test('isfunction', function (done) {



assert.deepEqual(ubique.isfunction(function(a){return console.log(a)}),true);
assert.deepEqual(ubique.isfunction(Math.log),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->