var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/isnumber ...');
test('isnumber', function (done) {



assert.deepEqual(ubique.isnumber(5),true);
assert.deepEqual(ubique.isnumber(NaN),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->