var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/isscalar ...');
test('isscalar', function (done) {



assert.deepEqual(ubique.isscalar(2),true);
assert.deepEqual(ubique.isscalar([2]),true);
assert.deepEqual(ubique.isscalar([[2]]),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->