var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/issingular ...');
test('issingular', function (done) {



assert.deepEqual(ubique.issingular([[2,6],[1,3]]),false);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->