var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/isvector ...');
test('isvector', function (done) {



assert.deepEqual(ubique.isvector([[5,6,7]]),true);
assert.deepEqual(ubique.isvector([[5],[6],[7]]),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->