var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/strfind ...');
test('strfind', function (done) {

var mystr = 'find indices in the string';

assert.deepEqual(ubique.strfind(mystr,'in'),[1,5,13,23]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->