var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/vectorfun ...');
test('vectorfun', function (done) {

var testfun = function(a,b,c){return ubique.mean(a)*b+c;};

assert.deepEqual(ubique.vectorfun(0,[[5,6,5],[7,8,-1]],testfun,5,10),[[36.666666666666664],[33.333333333333336]]);
assert.deepEqual(ubique.vectorfun(1,[[5,6,5],[7,8,-1]],testfun,5,10),[[40,45,20]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->