var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/weekday ...');
test('weekday', function (done) {



assert.deepEqual(ubique.weekday(1424708525),1);
assert.deepEqual(ubique.weekday([1414886399,1414972799]),[6,7]);
assert.deepEqual(ubique.weekday([[1414886399,1414972799],[1415059199,1415145599]]),[[6,7],[1,2]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->