var assert = require('assert');
var ubique = require('../../index.js');

suite('datatype',function () {
console.log('Testing datatype/weekday ...');
test('weekday', function (done) {



assert.deepEqual(ubique.weekday(1426636800),3);
assert.deepEqual(ubique.weekday([ 1424908800, 1426636800 ]),[4,3]);
assert.deepEqual(ubique.weekday([ [ 1424908800, 1426636800 ], [ 1427328000, 1429315200 ] ]),[[4,3],[4,6]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->