var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/cat ...');
test('cat', function (done) {

var a = [[5,6,5],[7,8,-1]];
var b = [[-1,3,-1],[4,5,9]];
var c = [5,6,3];
var d = [0.5,-3,2.3];
var f = [[3, 2], [5, 2]];

assert.deepEqual(ubique.cat(0,1,2,3,4),[[1],[2],[3],[4]]);
assert.deepEqual(ubique.cat(0,1,2,[3],4),[[1],[2],[3],[4]]);
assert.deepEqual(ubique.cat(0,1,2,[[3],[4]]),[[1],[2],[3],[4]]);
assert.deepEqual(ubique.cat(0,[1],2,3,[4]),[[1],[2],[3],[4]]);
assert.deepEqual(ubique.cat(0,c,d),[[5,6,3],[0.5,-3,2.3]]);
assert.deepEqual(ubique.cat(0,c,d,a),[[5,6,3],[0.5,-3,2.3],[5,6,5],[7,8,-1]]);
assert.deepEqual(ubique.cat(0,[[1]],[2],3,4),[[1],[2],[3],[4]]);
assert.deepEqual(ubique.cat(0,a,c),[[5,6,5],[7,8,-1],[5,6,3]]);
assert.deepEqual(ubique.cat(1,1,2,3,4),[[1,2,3,4]]);
assert.deepEqual(ubique.cat(1,1,2,[3],4),[[1,2,3,4]]);
assert.deepEqual(ubique.cat(1,1,2,[3,4]),[[1,2,3,4]]);
assert.deepEqual(ubique.cat(1,[1],2,3,4),[[1,2,3,4]]);
assert.deepEqual(ubique.cat(1,[[1]],2,3,4),[[1,2,3,4]]);
assert.deepEqual(ubique.cat(1,c,5),[[5,6,3,5]]);
assert.deepEqual(ubique.cat(1,c,d),[[5,6,3,0.5,-3,2.3]]);
assert.deepEqual(ubique.cat(1,[[2,3,4,5]],c,d),[[2,3,4,5,5,6,3,0.5,-3,2.3]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->