var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/clone ...');
test('clone', function (done) {



assert.deepEqual(ubique.clone([[-1,3,-1],[4,5,9]]),[[-1,3,-1],[4,5,9]]);
assert.deepEqual(ubique.clone([5,6,3]),[5,6,3]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->