var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/fix ...');
test('fix', function (done) {



assert.deepEqual(ubique.fix(3.78),3);
assert.deepEqual(ubique.fix([4.51,-1.4]),[4,-1]);
assert.deepEqual(ubique.fix([[4.51,-1.4],[3.78,0.01]]),[[4,-1],[3,0]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->