var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/fliplr ...');
test('fliplr', function (done) {



assert.deepEqual(ubique.fliplr([[1,4],[2,5],[3,6]]),[[1,4],[2,5],[3,6]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->