var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/flipud ...');
test('flipud', function (done) {



assert.deepEqual(ubique.flipud([[1,4],[2,5],[3,6]]),[[3,6],[2,5],[1,4]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->