var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/flipdim ...');
test('flipdim', function (done) {



assert.deepEqual(ubique.flipdim([5,6,3],1),[3,6,5]);
assert.deepEqual(ubique.flipdim([5,6,3],0),[5,6,3]);
assert.deepEqual(ubique.flipdim([[5,6,5],[7,8,-1]]),[[5,6,5],[-1,8,7]]);
assert.deepEqual(ubique.flipdim([[5,6,5],[7,8,-1]],0),[[7,8,-1],[5,6,5]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->