var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/issquare ...');
test('issquare', function (done) {



assert.deepEqual(ubique.issquare([[9, 5], [6, 1]]),true);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->