var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/linspace ...');
test('linspace', function (done) {



assert.deepEqual(ubique.linspace(1,10,5),[1,3.25,5.5,7.75,10]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->