var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/mergesort ...');
test('mergesort', function (done) {



assert.deepEqual(ubique.mergesort([[9,-3,2,-12,0,1],[0,1,2,3,4,5]]),[[-12,-3,0,1,2,9],[3,1,4,5,2,0]]);
assert.deepEqual(ubique.mergesort([9,-3,2,-12,0,1]),[[-12,-3,0,1,2,9],[3,1,4,5,2,0]]);
assert.deepEqual(ubique.mergesort([9,-3,2,-12,0,1],'descend'),[[9,2,1,0,-3,-12],[0,2,5,4,1,3]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->