var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/ncols ...');
test('ncols', function (done) {



assert.deepEqual(ubique.ncols([5,6,7]),3);
assert.deepEqual(ubique.ncols([[3,2,7],[4,5,6]]),3);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->