var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/numel ...');
test('numel', function (done) {



assert.deepEqual(ubique.numel([3,5,6]),3);
assert.deepEqual(ubique.numel([[3,2,7],[4,5,6]]),6);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->