var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/ones ...');
test('ones', function (done) {



assert.deepEqual(ubique.ones(0),[]);
assert.deepEqual(ubique.ones(1),[[1]]);
assert.deepEqual(ubique.ones(2),[[1,1],[1,1]]);
assert.deepEqual(ubique.ones([2,1]),[[1],[1]]);
assert.deepEqual(ubique.ones(2,3),[[1,1,1],[1,1,1]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->