var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/repmat ...');
test('repmat', function (done) {

var l = [[1,1,-1],[1,-2,3],[2,3,1]];

assert.deepEqual(ubique.repmat(10,3),[[10,10,10],[10,10,10],[10,10,10]]);
assert.deepEqual(ubique.repmat(0.5,3,2),[[0.5,0.5],[0.5,0.5],[0.5,0.5]]);
assert.deepEqual(ubique.repmat([5,6,3],1,2),[[5,6,3,5,6,3]]);
assert.deepEqual(ubique.repmat([[9, 5],[6, 1]],2),[[9,5,9,5],[6,1,6,1],[9,5,9,5],[6,1,6,1]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->