var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/reshape ...');
test('reshape', function (done) {



assert.deepEqual(ubique.reshape([5,6,3],3,1),[[5],[6],[3]]);
assert.deepEqual(ubique.reshape([5,6,3],1,3),[5,6,3]);
assert.deepEqual(ubique.reshape([[-1,3,-1],[4,5,9]],3,2),[[-1,4],[3,5],[-1,9]]);
assert.deepEqual(ubique.reshape([[-1,3,-1],[4,5,9]],3,2,1),[[-1,5],[4,-1],[3,9]]);
assert.deepEqual(ubique.reshape([[-1,3,-1],[4,5,9]],6,1),[[-1],[3],[-1],[4],[5],[9]]);
assert.deepEqual(ubique.reshape([[-1,3,-1],[4,5,9]],6,1,1),[[-1],[4],[3],[5],[-1],[9]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->