var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/tomat ...');
test('tomat', function (done) {



assert.deepEqual(ubique.tomat(5),[[5]]);
assert.deepEqual(ubique.tomat([5,6,3]),[[5,6,3]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->