var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/transpose ...');
test('transpose', function (done) {



assert.deepEqual(ubique.transpose([[5,6,5],[7,8,-1]]),[[5,7],[6,8],[5,-1]]);
assert.deepEqual(ubique.transpose([5,6,3]),[[5],[6],[3]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->