var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/trues ...');
test('trues', function (done) {



assert.deepEqual(ubique.trues(0),[]);
assert.deepEqual(ubique.trues(1),[[true]]);
assert.deepEqual(ubique.trues(2),[[true,true],[true,true]]);
assert.deepEqual(ubique.trues([2,1]),[[true],[true]]);
assert.deepEqual(ubique.trues(2,3),[[true,true,true],[true,true,true]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->