var assert = require('assert');
var ubique = require('../../index.js');

suite('matarrs',function () {
console.log('Testing matarrs/vertcat ...');
test('vertcat', function (done) {



assert.deepEqual(ubique.vertcat([[5,6,5],[7,8,-1]],[[-1,3,-1],[4,5,9]]),[[5,6,5],[7,8,-1],[-1,3,-1],[4,5,9]]);
assert.deepEqual(ubique.vertcat(5,7,9,8),[[5],[7],[9],[8]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->