var assert = require('assert');
var ubique = require('../../index.js');

suite('probdistr',function () {
console.log('Testing probdistr/jbtest ...');
test('jbtest', function (done) {



assert.deepEqual(ubique.jbtest(x),null);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->