var assert = require('assert');
var ubique = require('../../index.js');

suite('probdistr',function () {
console.log('Testing probdistr/norminv ...');
test('norminv', function (done) {

var x = [ 0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];

assert.deepEqual(ubique.norminv(0.05),-1.6448536127562647);
assert.deepEqual(ubique.norminv(0.01,ubique.mean(x),ubique.std(x)),-0.036142194809296924);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->