var assert = require('assert');
var ubique = require('../../index.js');

suite('probdistr',function () {
console.log('Testing probdistr/normcdf ...');
test('normcdf', function (done) {

var x = [ 0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];

assert.deepEqual(ubique.normcdf(2),0.9772498701098755);
assert.deepEqual(ubique.normcdf(0,ubique.mean(x),ubique.std(x)),0.22049006438883678);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->