var assert = require('assert');
var ubique = require('../../index.js');

suite('probdistr',function () {
console.log('Testing probdistr/normpdf ...');
test('normpdf', function (done) {

var x = [ 0.003,0.026,0.015,-0.009,0.014,0.024,0.015,0.066,-0.014,0.039];

assert.deepEqual(ubique.normpdf(1),0.24197072451914337);
assert.deepEqual(ubique.normpdf(0, ubique.mean(x),ubique.std(x)),12.762177621632251);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->