var assert = require('assert');
var ubique = require('../../index.js');

suite('datafeed',function () {
console.log('Testing datafeed/yahoo ...');
test('yahoo', function (done) {





done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->