var assert = require('assert');
var ubique = require('../../index.js');

suite('datafeed',function () {
console.log('Testing datafeed/yahooSync ...');
test('yahooSync', function (done) {

var options = { 'symbol': 'AAPL', 'from': '2015-01-02', 'to': '2015-01-08', 'period': 'd', 'fmt': 'YYYY-MM-DD' };

assert.deepEqual(ubique.yahooSync.historical(options),{"symbol":"AAPL","from":"2015-01-02","to":"2015-01-08","period":"d","date":["2015-01-02","2015-01-05","2015-01-06","2015-01-07","2015-01-08"],"open":[111.39,108.29,106.54,107.2,109.23],"high":[111.44,108.65,107.43,108.2,112.15],"low":[107.35,105.41,104.63,106.7,108.7],"close":[109.33,106.25,106.26,107.75,111.89],"volume":[53204600,64285500,65797100,40105900,59364500],"adjclose":[108.44723,105.3921,105.40202,106.87998,110.98656]});


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->