var assert = require('assert');
var ubique = require('../../index.js');

suite('reglin',function () {
console.log('Testing reglin/interp1 ...');
test('interp1', function (done) {

var x = [1,2,3,4,5,6];
var y = [2,4,6,8,10,12];
var xnew = [2,4,6];

assert.deepEqual(ubique.interp1(x,y,xnew),[4,8,12]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->