var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/cummax ...');
test('cummax', function (done) {



assert.deepEqual(ubique.cummax([5,6,3]),[5,6,6]);
assert.deepEqual(ubique.cummax([[5,6,5],[7,8,-1]]),[[5,6,5],[7,8,5]]);
assert.deepEqual(ubique.cummax([[5,6,5],[7,8,-1]],0),[[5,6,6],[7,8,8]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->