var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/diff ...');
test('diff', function (done) {



assert.deepEqual(ubique.diff([5,6,3]),[1,-3]);
assert.deepEqual(ubique.diff([[5,6,5],[7,8,-1]]),[[2,2,-6]]);
assert.deepEqual(ubique.diff([[5,6,5],[7,8,-1]],0),[[1,-1],[1,-9]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->