var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/dot ...');
test('dot', function (done) {



assert.deepEqual(ubique.dot([5,6,3],[0.5,-3,2.3]),-8.600000000000001);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->