var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/dot ...');
test('dot', function (done) {

var c = [5,6,3];
var d = [0.5,-3,2.3];

assert.deepEqual(ubique.dot(c,d),-8.600000000000001);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->