var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/lt ...');
test('lt', function (done) {



assert.deepEqual(ubique.lt(5,5),false);
assert.deepEqual(ubique.lt(5,[5,6,3]),[false,true,false]);
assert.deepEqual(ubique.lt(5,[[5,6],[3,5]]),[[false,true],[false,false]]);
assert.deepEqual(ubique.lt([5,6,3],5),[false,false,true]);
assert.deepEqual(ubique.lt([[5,6],[3,5]],5),[[false,false],[true,false]]);
assert.deepEqual(ubique.lt([5,6,3],[2,6,0]),[false,false,false]);
assert.deepEqual(ubique.lt([[5,6],[-1,2]],[[5,6],[3,5]]),[[false,false],[true,true]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->