var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/mrdivide ...');
test('mrdivide', function (done) {



assert.deepEqual(ubique.mrdivide(5,6),0.8333333333333334);
assert.deepEqual(ubique.mrdivide([5,6,3],6),[0.8333333333333334,1,0.5]);
assert.deepEqual(ubique.mrdivide([[9, 5], [6, 1]],5),[[1.8,1],[1.2,0.2]]);
assert.deepEqual(ubique.mrdivide([[9, 5], [6, 1]],[[3, 2], [5, 2]]),[[1.75,0.7500000000000004],[-1.75,2.25]]);
assert.deepEqual(ubique.mrdivide([[5,6,5],[7,8,-1]],[[1,1,-1],[1,-2,3],[2,3,1]]),[[-0.7692307692307696,0.5384615384615385,2.615384615384615],[3.384615384615384,0.230769230769231,1.6923076923076918]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->