var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/mtimes ...');
test('mtimes', function (done) {



assert.deepEqual(ubique.mtimes(5,6),30);
assert.deepEqual(ubique.mtimes([5,6,3],3),[15,18,9]);
assert.deepEqual(ubique.mtimes([[5,6,5],[7,8,-1]],3),[[15,18,15],[21,24,-3]]);
assert.deepEqual(ubique.mtimes([[5,6,3]],[[3],[4],[5]]),[[54]]);
assert.deepEqual(ubique.mtimes([[5,6,5],[7,8,-1]],[[5],[6],[3]]),[[76],[80]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->