var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/prod ...');
test('prod', function (done) {



assert.deepEqual(ubique.prod([5,6,3]),90);
assert.deepEqual(ubique.prod([[5,6,5],[7,8,-1]],0),[[150],[-56]]);
assert.deepEqual(ubique.prod([[5,6,5],[7,8,-1]],1),[[35,48,-5]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->