var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/times ...');
test('times', function (done) {



assert.deepEqual(ubique.times(5,6),30);
assert.deepEqual(ubique.times([5,6,4],[3,-1,0]),[15,-6,0]);
assert.deepEqual(ubique.times([5,6,4],10),[50,60,40]);
assert.deepEqual(ubique.times([[5,6,5],[7,8,-1]],[[-1,3,-1],[4,5,9]]),[[-5,18,-5],[28,40,-9]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->