var assert = require('assert');
var ubique = require('../../index.js');

suite('elemop',function () {
console.log('Testing elemop/unique ...');
test('unique', function (done) {



assert.deepEqual(ubique.unique([9,-3,2,-12,0,1,0,1,2,3,4,5]),[-3,-3,0,1,2,3,4,5,9]);
assert.deepEqual(ubique.unique([9,-3,2,-12,0,1,0,1,2,3,4,5],1),[[-3,-3,0,1,2,3,4,5,9],[3,1,4,5,2,9,10,11,0]]);
assert.deepEqual(ubique.unique([[5,4],[5,3],[6,3]]),[3,4,5,6]);
assert.deepEqual(ubique.unique([[5,4],[5,3],[6,3]],1),[[3,4,5,6],[3,1,0,4]]);


done();
});
});


// <--- This file has been auto-generated. PLEASE DO NOT EDIT THIS FILE, changes will be overwritten the next time the script is run --->